FROM ubuntu:18.04

RUN apt-get update && apt-get -y install python3-alembic python3-dateutil python3-prettytable python3-psutil python3-setproctitle python3-shortuuid python3-sqlalchemy netcat gettext-base
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-boto python3-azure-storage

VOLUME [ "/backup-source" ]
VOLUME [ "/var/lib/backy2" ] 

#source Ceph RBD image to be backup (rbd://<pool>/<imagename>[@<snapshotname>]) OR
#source file to be backup (file:///backup-source/TESTFILE)
ENV SOURCE_DATA_PATH ''

#file (will store in /var/lib/backy2/data)
#s3 (must be configured with ENVs below)
ENV TARGET_DATA_BACKEND 'file'

ENV S3_AWS_ACCESS_KEY_ID ''
ENV S3_AWS_SECRET_ACCESS_KEY ''
ENV S3_AWS_HOST ''
ENV S3_AWS_PORT '443'
ENV S3_AWS_HTTPS 'true'
ENV S3_AWS_BUCKET_NAME ''

ENV AZURE_ACCESS_KEY_ID ''
ENV AZURE_SECRET_ACCESS_KEY ''
ENV AZURE_BUCKET_NAME ''

ENV SIMULTANEOUS_WRITES '3'
ENV MAX_BANDWIDTH_WRITE '0'
ENV SIMULTANEOUS_READS '10'
ENV MAX_BANDWIDTH_READ '0'
ENV PROTECT_YOUNG_BACKUP_DAYS '6'

ENV PRE_POST_TIMEOUT '7200'
ENV PRE_BACKUP_COMMAND ''
ENV POST_BACKUP_COMMAND ''
ENV INDEX_DB_ADDRESS 'sqlite:////var/lib/backy2/backy.sqlite'

RUN touch /var/log/backy.log

CMD [ "tail", "-f", "/dev/null" ]
